baseURL = "https://abelazo.github.io/blog"
languageCode = "en-us"
title = "Abelazo's Blog"
theme = "ananke"

[params]
  twitter = "https://twitter.com/abelazog"
  github = "https://github.com/abelazo"
